language: python
python:
  - 2.7
  - 3.3
sudo: false
env:
  - DJANGO_VERSION=1.4.22
  - DJANGO_VERSION=1.5.12
  - DJANGO_VERSION=1.6.11
  - DJANGO_VERSION=1.7.10
  - DJANGO_VERSION=1.8.4
  - DJANGO_VERSION=1.9a1
matrix:
  allow_failures:
    - python: 3.3
#      env: DJANGO_VERSION=1.9a1
before_install:
  - if [ $TRAVIS_PYTHON_VERSION == 3.3 ]; then sed -ie "s/^robotframework$/robotframework-python3/g" requirements.txt; fi
install:
  - cat requirements.txt
  - pip install -r requirements.txt
  - pip install -q flake8
  - pip install -q  --pre Django==$DJANGO_VERSION
  - python setup.py install
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - pybot DjangoLibrary/tests/
  - flake8 .
after_script:
  - firefox --version
